#+title: Software

[[https://travis-ci.com/ConcaveTeam/software][https://travis-ci.com/ConcaveTeam/software.svg?branch=master]]

* Source Installation
For a docker image instead, see the next section.

- Install [[http://wiki.ros.org/][ROS]]
- =cd <your_catkin_ws>/src>=
- Clone this project: =git clone https://github.com/ConcaveTeam/software.git=
- Navigate back to the catkin works pace root: =cd ..=
- Install dependencies: =rosdep install -iry --from-paths src=
- Build the platform: =catkin_make=
- Done.
  Now you can run one of the modes in the section below.
  
* Alternative Install: Docker Installation
To get the environment in docker, simply run

```
docker run -it --rm --privileged --net=host concavegit/concaveturret
```

and run a mode of operation described below in the prompt.

* Modes of Operation

** Monocular Motion Tracking
- Command :: =roslaunch concaveteam trackmono.launch=
- View annotated image :: =rosrun rqt_image_view rqt_image_view trackmono=
- View published point :: =rosrun rviz rviz=, hit =Add=,  select =PointStamped=, expand the triangle under the new PointStamped heading on the left, and select =/target=..
     You will need to zoom out, point the camera along the axis, and increase the radius of the point to around 100 for an easy view.

This publishes an annotated image with moving objects circled in =/monotrack=, the most significant point in image coordinates called =target=, and the spherical angles denoting the location of the coordinates in degrees in =aim=

* Stereo Vision

** Launch stereo setup
- Hardware :: Mount the cameras. Plug in , in order, the left camera, and then the right camera.
- Launch the nodes :: =roslaunch concaveteam stereo.launch=
- View disparity map :: =rosrun image_view disparity_view image:=stereo/disparity==

This publishes a disparity map from our camera setup, as well as a point cloud in =/stereo/points2= which can be viewed in RVIZ.
